/*
 * Created on 27 sept. 2016 ( Time 21:28:14 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.gardecote.controllers;
import org.springframework.security.access.annotation.Secured;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;

import org.springframework.web.bind.annotation.RequestMapping;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.HashMap;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.beans.factory.annotation.Autowired;
import com.gardecote.LicenceAc;
import com.gardecote.business.service.qCarnetService;
import com.gardecote.business.service.qConcessionService;
import com.gardecote.business.service.qConsignataireService;
import com.gardecote.business.service.qEnginPecheService;
import com.gardecote.business.service.qEspeceService;
import com.gardecote.business.service.qJourMereService;
import com.gardecote.business.service.qZoneService;
import com.gardecote.business.service.qLicenceService;
import com.gardecote.business.service.qModelJPService;
import com.gardecote.business.service.qPageCarnetService		;
import com.gardecote.business.service.qTypeConcessionService;
import com.gardecote.business.service.qCategRessourceService;
import com.gardecote.business.service.qDocService;
import com.gardecote.business.service.qEspeceTypeeService;
import com.gardecote.business.service.qJourDebService;
import com.gardecote.business.service.qNationService;
import com.gardecote.business.service.qRegistreNavireService;
import com.gardecote.business.service.qSeqService;
import com.gardecote.business.service.qTypeLicService;
import com.gardecote.business.service.qTypeNavService;
/**
 * Spring MVC controller for 'LicencesBatlast' management.
 */
@Controller

public class mainJsp  {

	@Autowired
	private qCarnetService carnetService;
	@Autowired
	private qConcessionService concessionService;
	@Autowired
	private qConsignataireService consignataireService;
	@Autowired
	private qEnginPecheService enginsPecheService;

	@Autowired
	private qEspeceService especesService;
	@Autowired
	private qJourMereService jourMereService;
	@Autowired
	private qLicenceService licenceService;
	@Autowired
	private qModelJPService modeljpService;
	@Autowired
	private qPageCarnetService pagecarnetService;

	@Autowired
	private qTypeConcessionService typeconcessionService;
	@Autowired
	private qZoneService zoneService;

	@Autowired
	private qCategRessourceService categService;
	@Autowired
	private qDocService docService;
	@Autowired
	private qEspeceTypeeService especeService;
	@Autowired
	private qJourDebService   jourdebService;
	@Autowired
	private qNationService  nationService;

	@Autowired
	private qRegistreNavireService registrenavireService;
	@Autowired
	private qSeqService seqService;
	@Autowired
	private qTypeLicService typelicService;
	@Autowired
	private qTypeNavService typenavService;

	@Autowired
	private LicenceAc ourLic;

	@Secured(value={"ROLE_admin"})
	@RequestMapping("/start")
	public String list(Model model,HttpServletRequest httpServletRequest) {

		HttpSession httpSession=httpServletRequest.getSession();

		Authentication auth = SecurityContextHolder.getContext().getAuthentication();
		String username = auth.getName();
		List<String> roles=new ArrayList<>();
		for(GrantedAuthority ga:auth.getAuthorities()){
			roles.add(ga.getAuthority());
		}

		Map<String,Object> params=new HashMap<>();
		params.put("username",username);
		params.put("roles",roles);
	//	params.put("exp",ourLic.getLicAc().getLicenseText().getLicenseExpireDate().toString());
	//	ourLic.getLicAc().getValidationStatus().toString()
	//	params.put("validationStatus",true);
    //  params.put("Lic",ourLic.getLicAc());
		System.out.println("rest :");
	//	System.out.println(ourLic.getLicAc().getLicenseText().getLicenseExpireDate());

		model.addAttribute("infos",params);
		System.out.println(params);
		return "index";
	}

	

}