/*
 * Created on 27 sept. 2016 ( Time 21:28:14 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.gardecote.controllers;
import org.springframework.security.access.annotation.Secured;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;

import org.springframework.web.bind.annotation.RequestMapping;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.HashMap;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.beans.factory.annotation.Autowired;
import com.gardecote.LicenceAc;

/**
 * Spring MVC controller for 'LicencesBatlast' management.
 */
@Controller

public class mainJsp  {


	@Autowired
	private LicenceAc ourLic;

	@Secured(value={"ROLE_admin"})
	@RequestMapping("/start")
	public String list(Model model,HttpServletRequest httpServletRequest) {

		HttpSession httpSession=httpServletRequest.getSession();

		Authentication auth = SecurityContextHolder.getContext().getAuthentication();
		String username = auth.getName();
		List<String> roles=new ArrayList<>();
		for(GrantedAuthority ga:auth.getAuthorities()){
			roles.add(ga.getAuthority());
		}

		Map<String,Object> params=new HashMap<>();
		params.put("username",username);
		params.put("roles",roles);
	//	params.put("exp",ourLic.getLicAc().getLicenseText().getLicenseExpireDate().toString());
	//	ourLic.getLicAc().getValidationStatus().toString()
	//	params.put("validationStatus",true);
    //  params.put("Lic",ourLic.getLicAc());
		System.out.println("rest :");
	//	System.out.println(ourLic.getLicAc().getLicenseText().getLicenseExpireDate());

		model.addAttribute("infos",params);
		System.out.println(params);
		return "index";
	}

	

}