package com.gardecote.entities;

/**
 * Created by Dell on 09/10/2016.
 */

public enum enumCategRessource {
    PA_Cephalopode,
    PA_Crustaces,
    PA_Poissons_demersaux,
    PA_Poissons_Pelagique,
    PA_Algues_et_autres_Mollusques,

    PC_Cepholopode,
    PC_Crustaces,
    PC_Poissons_demersaux,
    PC_Poissons_Pelagiques_Seg1,
    PC_Poissons_Pelagiques_Seg2,
    PC_Poissons_Pelagiques_Seg3,
    PC_Autres_Mollusques,

    PH_Pelagique,
    PH_Thons,
    PH_Cephalopode,
    PH_Crevettes,
    PH_Merlus,
    PH_Poissons_demersaux_autre_que_merlu,
    PH_Langouste_rose,
    PH_Crabe_profond,
    PH_Autres_Mollusques,

    Affrete_Artisnal,
    Affrete_Collecte_peche_artisanal,
    Affreté_Demarsal_poisson_cephalopod,
    Affreté_Demarsal_cepal_crust,
    Affreté_Langouste,
    Affrete_Merlu,
    Affrete_Pelagique,
    Affrete_Thon,
    Affrete_Crabes,
    Affrete_Coquillage,
    Affrete_Recherche,
    Affrete_Requin,
    Affrete_Crevettes,
    Affrete_Crevetes_langoustes,
    Affreté_Demarsal_langouste_verte,
    Licence_Artisnal,
    Licence_Collecte_peche_artisanal,
    Licence_Demarsal_poisson_cephalopod,
    Licence_Langouste,
    Licence_Merlu,
    Licence_Pelagique,
    Licence_Thon,
    Licence_Crustace_sauf_langouste,
    Licence_Crabes,
    Licence_Espéce_demersal_profonde,
    Licence_Coquillage,
    Licence_Recherche,
    Licence_Requin,
    Licence_Crevetes_langoustes,
    National_Artisnal,
    National_Collecte_peche_artisanal,
    National_Demarsal_poisson_cephalopod,
    National_Demarsal_cepal_crust,
    National_Langouste,
    National_Merlu,
    National_Pelagique,
    National_Thon,
    National_Crabes,
    National_Coquillage,
    National_Recherche,
    National_Requin,
    National_Crevettes,
    National_Crevetes_langoustes,
    Licence_Esp_Demersal_autre_que_Merlu_Noir,
    Licence_Esp_Demersal,
    AU,
    Licence_Thons_Espadons,
    NN,
    NI,
    NU,
    LT,
    XP,
    Indeterminee,
    Licence_Indet,
    National_Indeter,
    Afffrété_Indeterminé,
    NATIONAL_RAVITAILLEUR_PELAGIQUE,
    AFFRETEMENT_EXP,
    National_Côtiere,
    Affrété_Espéce_demersal_profonde

   }