/*
 * Created on 8 oct. 2016 ( Time 01:00:05 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.gardecote.entities;

import org.springframework.format.annotation.DateTimeFormat;

import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

/**
 * Persistent class for entity stored in table "quotaJours"
 *
 * @author Telosys Tools Generator
 *
 */
import java.util.Date;
@Entity
@Table(name="qJourMere", schema="dbo", catalog="GCM11" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="qJour.countAll", query="SELECT COUNT(x) FROM qJourMere x" )
} )
@IdClass(qJourPK.class)
public class qJourMere implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="numimmJour", nullable=false)
    private String       numImm       ;
    @Id
    @Column(name="dateJour", nullable=false, length=10)
    @DateTimeFormat(pattern="yyyy-MM-dd")
    private Date     dateJour     ;
    @Id
    private Integer       indexLigne   ;
    @Id
    private String      numPage   ;
    private String secteur;
    @OneToOne
    private qNavireLegale navire;
    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    

   //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @OneToMany(mappedBy="jourMere", targetEntity=qCapture.class,cascade = CascadeType.ALL)
    @OrderBy("especeTypee.numOrdre ASC")
    private List<qCapture> capturesDuMarree;

    @Column(name="totalCapturs", nullable=false, length=10)
    private float totalCapturs;
    @Column(name="totalCong", nullable=false, length=10)
    private float totalCong;
    @Column(name="nbrCaisse", nullable=false, length=10)
    private float nbrCaisse;

    @ManyToOne
    private qPageMarree pageMarree;

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public qJourMere()
    {
		super();
    }

    public float getTotalCapturs() {
        return totalCapturs;
    }

    public void setTotalCapturs(Integer totalCapturs) {
        this.totalCapturs = totalCapturs;
    }

    public float getTotalCong() {
        return totalCong;
    }

    public void setTotalCong(Integer totalCong) {
        this.totalCong = totalCong;
    }

    public float getNbrCaisse() {
        return nbrCaisse;
    }

    public void setNbrCaisse(Integer nbrCaisse) {
        this.nbrCaisse = nbrCaisse;
    }

    public String getSecteur() {
        return secteur;
    }

    public void setSecteur(String secteur) {
        this.secteur = secteur;
    }

    public qJourMere(Integer idLigne, String numPage, Date datejourMere, qNavireLegale navire, List<qCapture> capturesDuMarree, float totalCapturs,float  totalCong,float  nbrCaisse, qPageMarree pageMarree) {
      this.indexLigne=idLigne;
        this.numPage=numPage;
        this.dateJour = datejourMere;
        this.capturesDuMarree = capturesDuMarree;
        this.totalCapturs = totalCapturs;
        this.totalCong = totalCong;
        this.nbrCaisse = nbrCaisse;
        this.numImm=navire.getNumimm();
        this.navire = navire;
        this.pageMarree=pageMarree;




    }

    public String getNumImm() {
        return numImm;
    }
    public qJourPK getJourMerPK(){
    qJourPK qjourpk=new qJourPK(this.getDatejourMere(),this.getNumImm().toString());
      return qjourpk;
    }
    public void setNumImm(String numImm) {
        this.numImm = numImm;
    }

    public qNavireLegale getNavire() {
        return navire;
    }

    public void setNavire(qNavireLegale navire) {
        this.navire = navire;
    }

    public Date getDatejourMere() {
        return dateJour;
    }

    public void setDatejourMere(Date datejourMere) {
        this.dateJour = datejourMere;
    }

    public List<qCapture> getCapturesDuMarree() {
        return capturesDuMarree;
    }

    public void setCapturesDuMarree(List<qCapture> capturesDuMarree) {
        this.capturesDuMarree = capturesDuMarree;
    }

    public Date getDateJour() {
        return dateJour;
    }

    public void setDateJour(Date dateJour) {
        this.dateJour = dateJour;
    }

    public qPageMarree getPageMarree() {
        return pageMarree;
    }

    public void setPageMarree(qPageMarree pageMarree) {
        this.pageMarree = pageMarree;
    }

    public Integer getIndexLigne() {
        return indexLigne;
    }

    public void setIndexLigne(Integer indexLigne) {
        this.indexLigne = indexLigne;
    }

    public String getNumPage() {
        return numPage;
    }

    public void setNumPage(String numPage) {
        this.numPage = numPage;
    }

    public void setTotalCapturs(float totalCapturs) {
        this.totalCapturs = totalCapturs;
    }

    public void setTotalCong(float totalCong) {
        this.totalCong = totalCong;
    }

    public void setNbrCaisse(float nbrCaisse) {
        this.nbrCaisse = nbrCaisse;
    }
}