/*
 * Created on 8 oct. 2016 ( Time 01:00:05 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.gardecote.entities;

import org.springframework.format.annotation.DateTimeFormat;

import javax.persistence.*;
import java.io.Serializable;
import java.util.Date;
import java.util.List;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;
/**
 * Persistent class for entity stored in table "quotaJours"
 *
 * @author Telosys Tools Generator
 */

@Entity
@Table(name="qJourMereAnnexe21", schema="dbo", catalog="GCM1" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="qJourAnnexe.countAll", query="SELECT COUNT(x) FROM qJourMereAnnexe x" )
} )
@IdClass(qJourPK.class)
public class qJourMereAnnexe implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="numimmJour", nullable=false)
    private String       numImm   ;

    @Id
    @Column(name="dateJour", nullable=false, length=10)
    @DateTimeFormat(pattern="yyyy-MM-dd")
    private Date     dateJour     ;

    @OneToOne
    private qNavire navire;
    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS
    //----------------------------------------------------------------------
   //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @OneToOne
    private qEspece especeDebarque;
    private Integer poidEnKg;
    private String presentation;
    @ManyToOne
    private qPageAnnexe pageMarree;

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public qJourMereAnnexe()
    {
		super();
    }
    public qJourMereAnnexe(Date datejourMere, qNavire navire,qEspece espece,Integer poids,String presentation,  qPageAnnexe pageMarree) {
        this.dateJour = datejourMere;
        this.especeDebarque=espece;
        this.poidEnKg=poids;
        this.presentation=presentation;
        this.numImm=navire.getNumimm();
        this.navire = navire;
        this.pageMarree=pageMarree;
   }

    public String getNumImm() {
        return numImm;
    }
    public qJourPK getJourMerPK(){
    qJourPK qjourpk=new qJourPK(this.getDatejourMere(),this.getNumImm().toString());
      return qjourpk;
    }
    public void setNumImm(String numImm) {
        this.numImm = numImm;
    }

    public qNavire getNavire() {
        return navire;
    }

    public void setNavire(qNavire navire) {
        this.navire = navire;
    }

    public Date getDatejourMere() {
        return dateJour;
    }

    public void setDatejourMere(Date datejourMere) {
        this.dateJour = datejourMere;
    }

    public Date getDateJour() {
        return dateJour;
    }

    public void setDateJour(Date dateJour) {
        this.dateJour = dateJour;
    }

    public qPageAnnexe getPageMarree() {
        return pageMarree;
    }

    public void setPageMarree(qPageAnnexe pageMarree) {
        this.pageMarree = pageMarree;
    }
}