/*
 * Created on 8 oct. 2016 ( Time 01:00:05 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.gardecote.entities;

import javax.persistence.*;
import java.io.Serializable;
import java.util.Date;
import java.util.List;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

/**
 * Persistent class for entity stored in table "quotaJours"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="qJourDeb", schema="dbo", catalog="DSPCM_DB" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="qJourDeb.countAll", query="SELECT COUNT(x) FROM qJour x" )
} )
public class qJourDeb implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="Id_Jour", nullable=false)
    private Long       idJourDeb       ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS
    //----------------------------------------------------------------------
    @Column(name="dateJour", nullable=false, length=10)
    private Date datejourDeb     ;
   //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @OneToMany(mappedBy="jour", targetEntity=qCapture.class)
    private List<qCapture> debarqDuJour;
    @OneToMany
    private List<qPageDebarquement> pagesDeb;

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public qJourDeb()
    {
		super();
    }

    public Long getIdJourDeb() {
        return idJourDeb;
    }

    public void setIdJourDeb(Long idJourDeb) {
        this.idJourDeb = idJourDeb;
    }

    public Date getDatejourDeb() {
        return datejourDeb;
    }

    public void setDatejourDeb(Date datejourDeb) {
        this.datejourDeb = datejourDeb;
    }

    public List<qCapture> getDebarqDuJour() {
        return debarqDuJour;
    }

    public void setDebarqDuJour(List<qCapture> debarqDuJour) {
        this.debarqDuJour = debarqDuJour;
    }

    public List<qPageDebarquement> getPagesDeb() {
        return pagesDeb;
    }

    public void setPagesDeb(List<qPageDebarquement> pagesDeb) {
        this.pagesDeb = pagesDeb;
    }
}