/*
 * Created on 8 oct. 2016 ( Time 01:00:05 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.gardecote.entities;

import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

/**
 * Persistent class for entity stored in table "quotaJours"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="qJour", schema="dbo", catalog="DSPCM_DB" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="qJour.countAll", query="SELECT COUNT(x) FROM qJour x" )
} )
public class qJour implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="Id_Jour", nullable=false)
    private Long       idJour       ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="dateJour", nullable=false, length=10)
    private String     datejour     ;
   //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @OneToMany(mappedBy="jour", targetEntity=qCapture.class)
    private List<qCapture> capturesDuJour;
@OneToMany
    private List<qPageCarnet> pages;

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public qJour()
    {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setIdJour( Long idJour )
    {
        this.idJour = idJour ;
    }
    public Long getIdJour()
    {
        return this.idJour;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : dateJour ( date ) 
    public void setDatejour( String datejour )
    {
        this.datejour = datejour;
    }
    public String getDatejour()
    {
        return this.datejour;
    }

    public List<qCapture> getCapturesDuJour() {
        return capturesDuJour;
    }

    public List<qPageCarnet> getPages() {
        return pages;
    }

    public void setPages(List<qPageCarnet> pages) {
        this.pages = pages;
    }

    public void setCapturesDuJour(List<qCapture> capturesDuJour) {
        this.capturesDuJour = capturesDuJour;
    }
//----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(idJour);
        sb.append("]:"); 
        sb.append(datejour);
        sb.append("|");

        return sb.toString(); 
    } 

}