/*
 * Created on 8 oct. 2016 ( Time 01:00:05 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.gardecote.entities;

import org.springframework.format.annotation.DateTimeFormat;

import javax.persistence.*;
import java.io.Serializable;
import java.util.Date;
import java.util.List;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;
/**
 * Persistent class for entity stored in table "quotaJours"
 *
 * @author Telosys Tools Generator
 */

@Entity
@Table(name="qJourMereAnnexe", schema="dbo", catalog="GCM5" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="qJourAnnexe.countAll", query="SELECT COUNT(x) FROM qJourMereAnnexe x" )
} )
@IdClass(qJourPK.class)
public class qJourMereAnnexe implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="numimmJour", nullable=false)
    private String       numImm   ;
    @Id
    @Column(name="dateJour", nullable=false, length=10)
    @DateTimeFormat(pattern="yyyy-MM-dd")
    private Date     dateJour     ;
    @Id
    @Column(name="indexLigne", nullable=false)
    private Integer       indexLigne   ;
    @Id
    private String      numPage   ;
    @OneToOne
    private qNavireLegale navire;
    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS
    //----------------------------------------------------------------------
   //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @OneToOne
    private qEspece especeDebarque;
    private String  designation;
    private Integer poidEnKg;
    private String presentation;
    @ManyToOne
    private qPageAnnexe pageMarree;

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public qJourMereAnnexe()
    {
		super();
    }

    public qJourMereAnnexe(Integer index,String numPage,String designation,Date datejourMere, qNavireLegale navire,qEspece espece,Integer poids,String presentation,  qPageAnnexe pageMarree) {
        this.dateJour = pageMarree.getQmarreeAnexe().getDepart();
        this.numPage=numPage;
        this.especeDebarque=espece;
        this.poidEnKg=poids;
        this.presentation=presentation;
        this.numImm=navire.getNumimm();
        this.navire = navire;
        this.pageMarree=pageMarree;
        this.indexLigne=index;
        this.designation=designation;
   }

    public Integer getIndexLigne() {
        return indexLigne;
    }

    public void setIndexLigne(Integer indexLigne) {
        this.indexLigne = indexLigne;
    }

    public qEspece getEspeceDebarque() {
        return especeDebarque;
    }

    public void setEspeceDebarque(qEspece especeDebarque) {
        this.especeDebarque = especeDebarque;
    }

    public String getDesignation() {
        return designation;
    }

    public void setDesignation(String designation) {
        this.designation = designation;
    }

    public Integer getPoidEnKg() {
        return poidEnKg;
    }

    public void setPoidEnKg(Integer poidEnKg) {
        this.poidEnKg = poidEnKg;
    }

    public String getPresentation() {
        return presentation;
    }

    public void setPresentation(String presentation) {
        this.presentation = presentation;
    }

    public String getNumPage() {
        return numPage;
    }

    public void setNumPage(String numPage) {
        this.numPage = numPage;
    }

    public String getNumImm() {
        return numImm;
    }
    public qJourPKAnnexe getJourMerPKAnnexe(){
    qJourPKAnnexe qjourpkAnnexe=new qJourPKAnnexe(this.getDatejourMere(),this.getNumImm().toString(),this.indexLigne);
      return qjourpkAnnexe;
    }
    public void setNumImm(String numImm) {
        this.numImm = numImm;
    }

    public qNavireLegale getNavire() {
        return navire;
    }

    public void setNavire(qNavireLegale navire) {
        this.navire = navire;
    }

    public Date getDatejourMere() {
        return dateJour;
    }

    public void setDatejourMere(Date datejourMere) {
        this.dateJour = datejourMere;
    }

    public Date getDateJour() {
        return dateJour;
    }

    public void setDateJour(Date dateJour) {
        this.dateJour = dateJour;
    }

    public qPageAnnexe getPageMarree() {
        return pageMarree;
    }

    public void setPageMarree(qPageAnnexe pageMarree) {
        this.pageMarree = pageMarree;
    }
}