/*
 * Created on 8 oct. 2016 ( Time 01:00:05 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.gardecote.entities;

import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

/**
 * Persistent class for entity stored in table "quotaJours"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="qJour", schema="dbo", catalog="DSPCM_DB" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="qJour.countAll", query="SELECT COUNT(x) FROM qJourMere x" )
} )
public class qJourMere implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="Id_Jour", nullable=false)
    private Long       idJourMere       ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="dateJour", nullable=false, length=10)
    private String     datejourMere     ;
   //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @OneToMany(mappedBy="jourMere", targetEntity=qCapture.class)
    private List<qCapture> capturesDuMarree;
    @OneToMany
    private List<qPageMarree> pagesMarree;

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public qJourMere()
    {
		super();
    }

    public Long getIdJourMere() {
        return idJourMere;
    }

    public void setIdJourMere(Long idJourMere) {
        this.idJourMere = idJourMere;
    }

    public String getDatejourMere() {
        return datejourMere;
    }

    public void setDatejourMere(String datejourMere) {
        this.datejourMere = datejourMere;
    }

    public List<qCapture> getCapturesDuMarree() {
        return capturesDuMarree;
    }

    public void setCapturesDuMarree(List<qCapture> capturesDuMarree) {
        this.capturesDuMarree = capturesDuMarree;
    }

    public List<qPageMarree> getPagesMarree() {
        return pagesMarree;
    }

    public void setPagesMarree(List<qPageMarree> pagesMarree) {
        this.pagesMarree = pagesMarree;
    }
}