/*
 * Created on 8 oct. 2016 ( Time 01:00:05 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.gardecote.entities;

import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

/**
 * Persistent class for entity stored in table "quotaPageCarnet"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="qPageCarnet", schema="dbo", catalog="DSPCM_DB" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="qPageCarnet.countAll", query="SELECT COUNT(x) FROM qPageCarnet x" )
} )
public class qPageCarnet implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
     // ENTITY DATA FIELDS
    //----------------------------------------------------------------------
    @Id
    @Column(name="numPage", nullable=false, length=50)
    private String     numeroPage      ;

	// "idcarnet" (column "IdCarnet") is not defined by itself because used as FK in a link 

    @OneToOne
    private qCategRessource     categRessource;

    @OneToOne
    private qMarree     qmarree;
    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="IdCarnet", referencedColumnName="IdCarnet")
    private qCarnet carnet;

    @OneToMany(mappedBy = "pages",targetEntity = qJour.class)
    private List<qJour>  listJours;

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public qPageCarnet()
    {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
   //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : numPage ( varchar ) 




    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setCarnet( qCarnet qcarnet )
    {
        this.carnet = qcarnet;
    }
    public qCarnet getCarnet()
    {
        return this.carnet;
    }

    public String getNumeroPage() {
        return numeroPage;
    }

    public void setNumeroPage(String numeroPage) {
        this.numeroPage = numeroPage;
    }

    public qCategRessource getCategRessource() {
        return categRessource;
    }

    public void setCategRessource(qCategRessource categRessource) {
        this.categRessource = categRessource;
    }

    public qMarree getQmarree() {
        return qmarree;
    }

    public void setQmarree(qMarree qmarree) {
        this.qmarree = qmarree;
    }

    public List<qJour> getListJours() {
        return listJours;
    }

    public void setListJours(List<qJour> listJours) {
        this.listJours = listJours;
    }

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("[");
        sb.append(numeroPage);
        sb.append("]:"); 

        return sb.toString(); 
    } 

}