/*
 * Created on 8 oct. 2016 ( Time 01:00:05 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.gardecote.entities;

import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

/**
 * Persistent class for entity stored in table "quotaPageCarnet"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="qPageCarnet", schema="dbo", catalog="DSPCM_DB" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="qPageCarnet.countAll", query="SELECT COUNT(x) FROM qPageCarnet x" )
} )
public class qPageCarnet implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
     // ENTITY DATA FIELDS
    //----------------------------------------------------------------------
    @Id
    @Column(name="numPage", nullable=false, length=50)
    private String     numeroPage      ;
    private Integer  nbrLigne ;

	// "idcarnet" (column "IdCarnet") is not defined by itself because used as FK in a link 

     //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="IdCarnet", referencedColumnName="IdCarnet")
    private qCarnet carnet;

    public qPageCarnet() {
    }

    public qPageCarnet(String numeroPage, Integer nbrLigne) {
        this.numeroPage = numeroPage;
        this.nbrLigne = nbrLigne;
    }

    public Integer getNbrLigne() {
        return nbrLigne;
    }

    public void setNbrLigne(Integer nbrLigne) {
        this.nbrLigne = nbrLigne;
    }

    public String getNumeroPage() {
        return numeroPage;
    }

    public void setNumeroPage(String numeroPage) {
        this.numeroPage = numeroPage;
    }

    public qCarnet getCarnet() {
        return carnet;
    }

    public void setCarnet(qCarnet carnet) {
        this.carnet = carnet;
    }


}