/*
 * Created on 26 sept. 2016 ( Time 10:51:46 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.gardecote.business.service;

import java.util.List;
import com.gardecote.entities.qCapture;
import com.gardecote.entities.qCapturePK;
/**
 * Business Service Interface for entity Activitebat.
 */
public interface qCapturesService {

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param idact
	 * @return entity
	 */
	qCapture findById(qCapturePK idact) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<qCapture> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	qCapture save(qCapture entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	qCapture update(qCapture entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	qCapture create(qCapture entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param idCapture
	 */
	void delete(qCapturePK idCapture);


}
