/*
 * Created on 26 sept. 2016 ( Time 10:51:46 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.gardecote.business.service;
import com.gardecote.entities.*;
import org.springframework.data.domain.Page;

import java.util.List;
/**
 * Business Service Interface for entity Authprov.
 */
public interface qCarnetService {
	/**
	 * Loads an entity from the database using its Primary Key
	 * @param idcapture
	 * @return entity
	 */
	qCarnet findById(qCarnetPK idcapture) ;

	public Page<qCarnet> findAll(int p, int size);
	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<qCarnet> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	qCarnet save(qCarnet entity);


	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	qCarnet update(qCarnet entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	qCarnet create(qCarnet entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param idauthpr
	 */
	void delete(qCarnetPK idauthpr);

	qCarnet entrerDansLeSystem(qCarnet carnet);

	qCarnet attribuerCarnetAuNavire(qCarnet carnet,qNavireLegale nav,qLic licence,qUsine usine);

    boolean checkIfNumeroDebutValable(Long numDebut);
}
