/*
 * Created on 26 sept. 2016 ( Time 10:18:28 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.gardecote.business.service;
import com.gardecote.entities.qCategRessource;
import java.util.List;

/**
 * Business Service Interface for entity AutorisEntity.
 */
public interface qCategRessourceService {

	/**
	 * Loads an entity from the database using its Primary Key
	 * @return entity
	 */
	qCategRessource findById(qCategRessourcePK qPK) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<qCategRessource> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	qCategRessource save(qCategRessource entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	qCategRessource update(qCategRessource entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	qCategRessource create(qCategRessource entity);

	/**
	 * Deletes an entity using its Primary Key
	 */
	void delete(qCategRessourcePK qPK);


}
