/*
 * Created on 26 sept. 2016 ( Time 10:51:47 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.gardecote.business.service;

import java.util.List;
import com.gardecote.entities.qConsignataire;
import org.springframework.data.domain.Page;

/**
 * Business Service Interface for entity Pvcom.
 */
public interface qConsignataireService {

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param idCondifnataire
	 * @return entity
	 */
	qConsignataire findById(String idCondifnataire) ;
	public Page<qConsignataire> findAll(int p, int size);
	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<qConsignataire> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	qConsignataire save(qConsignataire entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	qConsignataire update(qConsignataire entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	qConsignataire create(qConsignataire entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param idPvcomEntity
	 */
	void delete(String idPvcomEntity);


}
