/*
 * Created on 26 sept. 2016 ( Time 10:51:47 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.gardecote.business.service;
import com.gardecote.entities.qConcession;
import com.gardecote.entities.qConsignataire;
import org.springframework.data.domain.Page;

import java.util.List;

/**
 * Business Service Interface for entity Pvinfr.
 */
public interface qConcessionService {

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param refConcession
	 * @return entity
	 */
	boolean validate(String RefConcession);
	Page<qConcession> getSuggConcession(String searcconcession);

	qConcession findById(String refConcession) ;
	public Page<qConcession> findAll(int p, int size);
	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<qConcession> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	qConcession save(qConcession entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	qConcession update(qConcession entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	qConcession create(qConcession entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param refConcession
	 */
	void delete(String refConcession);


}
