/*
 * Created on 26 sept. 2016 ( Time 10:51:46 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.gardecote.business.service;


import com.gardecote.entities.qEnginPecheMar;
import com.gardecote.entities.qEnginPechePK;

import java.util.List;

/**
 * Business Service Interface for entity BateaucompletEntity.
 */
public interface qEnginPecheMarService {

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param numimm
	 * @return entity
	 */
	qEnginPecheMar findById(qEnginPechePK numimm) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<qEnginPecheMar> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	qEnginPecheMar save(qEnginPecheMar entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	qEnginPecheMar update(qEnginPecheMar entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	qEnginPecheMar create(qEnginPecheMar entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param numimm
	 */
	void delete(qEnginPechePK numimm);


}
