/*
 * Created on 26 sept. 2016 ( Time 10:51:46 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.gardecote.business.service;

import com.gardecote.entities.enumEngin;
import com.gardecote.entities.enumEnginDeb;

import com.gardecote.entities.qEnginPecheDebar;
import com.gardecote.entities.qEnginPechePK;

import java.util.List;

/**
 * Business Service Interface for entity BateaucompletEntity.
 */
public interface qEnginPecheDebarService {

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param numimm
	 * @return entity
	 */
	qEnginPecheDebar findById(qEnginPechePK  numimm) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<qEnginPecheDebar> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	qEnginPecheDebar save(qEnginPecheDebar entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	qEnginPecheDebar update(qEnginPecheDebar entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	qEnginPecheDebar create(qEnginPecheDebar entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param numimm
	 */
	void delete(qEnginPechePK numimm);


}
