/*
 * Created on 26 sept. 2016 ( Time 10:51:46 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.gardecote.business.service;
import com.gardecote.entities.qEnginPeche;
import java.util.List;

/**
 * Business Service Interface for entity BateaucompletEntity.
 */
public interface qEnginPecheService {

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param numimm
	 * @return entity
	 */
	qEnginPeche findById(Integer numimm) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<qEnginPeche> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	qEnginPeche save(qEnginPeche entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	qEnginPeche update(qEnginPeche entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	qEnginPeche create(qEnginPeche entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param numimm
	 */
	void delete(Integer numimm);


}
