/*
 * Created on 26 sept. 2016 ( Time 10:51:46 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.gardecote.business.service;
import com.gardecote.entities.qEspece;
import org.springframework.data.domain.Page;

import java.util.List;

/**
 * Business Service Interface for entity BatobservEntity.
 */
public interface qEspeceService {

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param idBatobs
	 * @return entity
	 */
	qEspece findById(String idBatobs) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<qEspece> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	qEspece save(qEspece entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	qEspece update(qEspece entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	qEspece create(qEspece entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param idBatobs
	 */
	Integer delete(String idBatobs);

	public Page<qEspece> getSuggEsp(String esp);
	public qEspece getSuggEspExact(String esp);
}
