/*
 * Created on 26 sept. 2016 ( Time 10:51:46 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.gardecote.business.service;

import java.util.List;

import com.gardecote.entities.qJourMere;
/**
 * Business Service Interface for entity Captures2.
 */
public interface qJourMereService {

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param idCapture
	 * @return entity
	 */
	qJourMere findById(Long idCapture) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<qJourMere> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	qJourMere save(qJourMere entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	qJourMere update(qJourMere entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	qJourMere create(qJourMere entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param idCapture
	 */
	void delete(Long idCapture);


}
