/*
 * Created on 26 sept. 2016 ( Time 10:51:46 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.gardecote.business.service;

import java.util.List;
import com.gardecote.entities.qJour;
/**
 * Business Service Interface for entity Captures2.
 */
public interface qJourService {

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param idCapture
	 * @return entity
	 */
	qJour findById(Long idCapture) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<qJour> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	qJour save(qJour entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	qJour update(qJour entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	qJour create(qJour entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param idCapture
	 */
	void delete(Long idCapture);


}
