/*
 * Created on 26 sept. 2016 ( Time 10:51:46 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.gardecote.business.service;

import org.springframework.data.domain.Page;

import java.util.List;
import com.gardecote.entities.qLicence;
/**
 * Business Service Interface for entity Changmentact.
 */
public interface qLicenceService {

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param idchact
	 * @return entity
	 */
	qLicence findById(Long idchact) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<qLicence> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	qLicence save(qLicence entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	qLicence update(qLicence entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	qLicence create(qLicence entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param idchact
	 */
	void delete(Long idchact);
	Page<qLicence> returnSuggNomNav(String searchNomnav);

}
