/*
 * Created on 26 sept. 2016 ( Time 10:51:46 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.gardecote.business.service;

import com.gardecote.entities.qLic;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.web.multipart.MultipartFile;

import javax.servlet.http.HttpServletRequest;
import java.util.List;

/**
 * Business Service Interface for entity Changmentact.
 */
public interface qLicenceService {

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param idchact
	 * @return entity
	 */
	qLic findById(String idchact) ;
	void  importerLicence(MultipartFile file, String fullname);
	/**
	 * Loads all entities.
	 * @return all entities
	 */
	Page<qLic> findAll(int p, int size);

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	qLic save(qLic entity);


	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	qLic update(qLic entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	qLic create(qLic entity);
	 boolean validatenav(qLic lic);
	boolean validatenumlic(qLic lic);
	/**
	 * Deletes an entity using its Primary Key
	 * @param idchact
	 */
	void delete(String idchact);
	Page<qLic> returnSuggNomNav(String searchNomnav);

}
