/*
 * Created on 26 sept. 2016 ( Time 10:51:46 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.gardecote.business.service;
import com.gardecote.entities.qMarree;
import java.util.List;
import com.gardecote.entities.qDocPK;
/**
 * Business Service Interface for entity Classinfractions.
 */
public interface qMarreeService {
	/**
	 * Loads an entity from the database using its Primary Key
	 * @param codeClass
	 * @return entity
	 */
	qMarree findById(qDocPK codeClass) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<qMarree> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	qMarree save(qMarree entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	qMarree update(qMarree entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	qMarree create(qMarree entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param codeClass
	 */
	void delete(qDocPK codeClass);


}
