/*
 * Created on 26 sept. 2016 ( Time 10:51:46 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.gardecote.business.service;
import com.gardecote.entities.*;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

import java.util.Date;
import java.util.List;

/**
 * Business Service Interface for entity Codauth.
 */
public interface qModelJPService {

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param codeauth
	 * @return entity
	 */

	qModelJP findById(qPrefixPK codeauth);
	List<qEspeceTypee>   findEspTypees(String pr);


	List<qEspeceDynamic> getEspecestypeesDyn(String numeroPage,enumTypeDoc  typeDoc, qModelJP md);
	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<qModelJP> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	qModelJP save(qModelJP entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	qModelJP update(qModelJP entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	qModelJP create(qModelJP entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param codeauth
	 */
	void delete(qPrefixPK  codeauth);


}
