/*
 * Created on 26 sept. 2016 ( Time 10:51:47 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.gardecote.business.service;
import com.gardecote.entities.enumTypeDoc;
import com.gardecote.entities.qDoc;
import com.gardecote.entities.qPageCarnet;
import com.gardecote.entities.qPageCarnetPK;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import java.util.ArrayList;
import java.util.List;

/**
 * Business Service Interface for entity CodeInfractions.
 */
public interface qPageCarnetService {

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param code
	 * @return entity
	 */
	Page<qPageCarnet> getSuggPageP(String numeroP);
	Page<qPageCarnet> getSuggPage(String searcpage,enumTypeDoc typeDoc);
	Page<qPageCarnet> getSuggPageAnnexe(String searcpage,enumTypeDoc typeDoc);
	ArrayList<qPageCarnet> getFinList(String debut,enumTypeDoc typeDoc);

	qPageCarnet findById(qPageCarnetPK code) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<qPageCarnet> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	qPageCarnet save(qPageCarnet entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	qPageCarnet update(qPageCarnet entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	qPageCarnet create(qPageCarnet entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param code
	 */
	void delete(qPageCarnetPK code);


}
