/*
 * Created on 27 sept. 2016 ( Time 01:48:09 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.gardecote.web.listitem;

import com.gardecote.web.common.ListItem;
import com.gardecote.entities.qLicenceBatLast;
public class LicencesBatlastListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public LicencesBatlastListItem(qLicenceBatLast licencesBatlast) {
		super();

		this.value = ""
			 + licencesBatlast.getIdLic()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = licencesBatlast.toString();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
