/*
 * Created on 27 sept. 2016 ( Time 22:01:25 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.gardecote.web.common;

public interface ListItem {

	public String getValue();
	
	public String getLabel();
}
