/*
 * Created on 27 sept. 2016 ( Time 22:01:25 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.gardecote.web.common;

public enum MessageType {
	
	SUCCESS,
	INFO,
	WARNING,
	DANGER;
	
	public String getCss() {
		return name().toLowerCase();
	}
	
}
