/*
 * Created on 26 sept. 2016 ( Time 10:51:46 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.gardecote.business.service.impl;
import com.gardecote.business.service.qCarnetService;
import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;




import com.gardecote.data.repository.jpa.qCarnetRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import com.gardecote.entities.qCarnet;
/**
 * Implementation of AuthprovService
 */
@Service
@Transactional
public class qCarnetServiceImpl implements qCarnetService {

	@Resource
	private qCarnetRepository qCarnetRepository;


	@Override
	public qCarnet findById(Long idcarnet) {
		qCarnet authprovEntity = qCarnetRepository.findOne(idcarnet);
		return authprovEntity;
	}

	@Override
	public List<qCarnet> findAll() {
		Iterable<qCarnet> entities = qCarnetRepository.findAll();
		List<qCarnet> beans = new ArrayList<qCarnet>();
		for(qCarnet authprovEntity1 : entities) {
			beans.add(authprovEntity1);
		}
		return beans;
	}

	@Override
	public qCarnet save(qCarnet authprov) {
		return update(authprov) ;
	}

	@Override
	public qCarnet create(qCarnet authprov) {
		qCarnet authprovEntity = qCarnetRepository.findOne(authprov.getIdcarnet());
		if( authprovEntity != null ) {
			throw new IllegalStateException("already.exists");
		}
		authprovEntity = new qCarnet();

		qCarnet authprovEntitySaved = qCarnetRepository.save(authprovEntity);
		return authprovEntitySaved;
	}

	@Override
	public qCarnet update(qCarnet authprov) {
		qCarnet authprovEntity = qCarnetRepository.findOne(authprov.getIdcarnet());

		qCarnet authprovEntitySaved = qCarnetRepository.save(authprovEntity);
		return authprovEntitySaved ;
	}

	@Override
	public void delete(Long idauthpr) {
		qCarnetRepository.delete(idauthpr);
	}

	public qCarnetRepository getAuthprovJpaRepository() {
		return qCarnetRepository;
	}

	public void setAuthprovJpaRepository(qCarnetRepository authprovJpaRepository) {
		this.qCarnetRepository = authprovJpaRepository;
	}


}
