/*
 * Created on 26 sept. 2016 ( Time 10:51:46 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.gardecote.business.service.impl;
import com.gardecote.business.service.qConsignataireService;
import java.util.ArrayList;
import java.util.List;
import com.gardecote.entities.qConsignataire;
import javax.annotation.Resource;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;


import com.gardecote.data.repository.jpa.qConsignataireRepository;
import com.gardecote.entities.qDoc;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * Implementation of BatobservService
 */

@Service
@Transactional
public class qConsignataireServiceImpl implements qConsignataireService {

	@Autowired
	private qConsignataireRepository batobservJpaRepository;
	@PersistenceContext
	private EntityManager em;
	
	@Override
	public qConsignataire findById(String idBatobs) {
		qConsignataire batobservEntity = batobservJpaRepository.findOne(idBatobs);
		return batobservEntity;
	}

	@Override
	public List<qConsignataire> findAll() {
		Iterable<qConsignataire> entities = batobservJpaRepository.findAll();
		List<qConsignataire> beans = new ArrayList<qConsignataire>();
		for(qConsignataire batobservEntity : entities) {
			beans.add(batobservEntity);
		}
		return beans;
	}
	@Override
	public Page<qConsignataire> findAll(int p, int size) {
		Page<qConsignataire> entities = batobservJpaRepository.findAll(new PageRequest(p, size));
		return entities;
	}
	@Override
	public qConsignataire save(qConsignataire batobserv) {
		return update(batobserv) ;
	}

	@Override
	public qConsignataire create(qConsignataire batobserv) {


	//	qConsignataire batobservEntitySaved = batobservJpaRepository.save(batobserv);
	//	return batobservEntitySaved;
		qConsignataire tt=em.find(qConsignataire.class,batobserv.getNomconsignataire());
		//      System.out.println(tt.toString());
		Integer i=0;

if(tt!=null)        System.out.println("dup :"+tt.getNomConsignataire());

		if (tt!=null){

			em.merge(batobserv);
		}else{

			em.persist(batobserv);
		}

		return batobservJpaRepository.save(batobserv);
	}

	@Override
	public qConsignataire update(qConsignataire batobserv) {
		qConsignataire batobservEntity = batobservJpaRepository.findOne(batobserv.getNomConsignataire());

		qConsignataire batobservEntitySaved = batobservJpaRepository.save(batobservEntity);
		return batobservEntitySaved;
	}

	@Override
	public void delete(String idBatobs) {
		batobservJpaRepository.delete(idBatobs);
	}

	public qConsignataireRepository getBatobservJpaRepository() {
		return batobservJpaRepository;
	}

	public void setBatobservJpaRepository(qConsignataireRepository batobservJpaRepository) {
		this.batobservJpaRepository = batobservJpaRepository;
	}

}
