/*
 * Created on 26 sept. 2016 ( Time 10:51:46 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.gardecote.business.service.impl;
import com.gardecote.business.service.qConcessionService;
import java.util.ArrayList;
import java.util.List;
import com.gardecote.entities.qConcession;

import com.gardecote.data.repository.jpa.qConcessionRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * Implementation of BateaucompletService
 */
@Service
@Transactional
public class qConcessionServiceImpl implements qConcessionService {

	@Autowired
	private qConcessionRepository qConcessionRepository;

	
	@Override
	public qConcession findById(String numimm) {
		qConcession bateaucompletEntity = qConcessionRepository.findOne(numimm);
		return bateaucompletEntity;
	}

	@Override
	public List<qConcession> findAll() {
		Iterable<qConcession> entities = qConcessionRepository.findAll();
		List<qConcession> beans = new ArrayList<qConcession>();
		for(qConcession bateaucompletEntity1 : entities) {
			beans.add(bateaucompletEntity1);
		}
		return beans;
	}

	@Override
	public qConcession save(qConcession bateaucomplet) {
		return update(bateaucomplet) ;
	}

	@Override
	public qConcession create(qConcession bateaucomplet) {
		qConcession bateaucompletEntity = qConcessionRepository.findOne(bateaucomplet.getRefConcession());
		if( bateaucompletEntity != null ) {
			throw new IllegalStateException("already.exists");
		}
		bateaucompletEntity = new qConcession();
		qConcession bateaucompletEntitySaved = qConcessionRepository.save(bateaucompletEntity);
		return bateaucompletEntitySaved;
	}

	@Override
	public qConcession update(qConcession bateaucomplet) {
		qConcession bateaucompletEntity = qConcessionRepository.findOne(bateaucomplet.getRefConcession());
		qConcession bateaucompletEntitySaved = qConcessionRepository.save(bateaucompletEntity);
		return bateaucompletEntitySaved;
	}

	@Override
	public void delete(String numimm) {
		qConcessionRepository.delete(numimm);
	}

	public qConcessionRepository getBateaucompletJpaRepository() {
		return qConcessionRepository;
	}

	public void setBateaucompletJpaRepository(qConcessionRepository bateaucompletJpaRepository) {
		this.qConcessionRepository = bateaucompletJpaRepository;
	}

	

}
