/*
 * Created on 26 sept. 2016 ( Time 10:51:46 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.gardecote.business.service.impl;


import com.gardecote.business.service.qEnginPecheDebarService;


import com.gardecote.data.repository.jpa.qEnginPecheDebarRepository;

import com.gardecote.entities.enumEngin;
import com.gardecote.entities.enumEnginDeb;

import com.gardecote.entities.qEnginPecheDebar;
import com.gardecote.entities.qEnginPechePK;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.ArrayList;
import java.util.List;

/**
 * Implementation of Captures2Service
 */
@Service
@Transactional
public class qEnginPecheDebarServiceImpl implements qEnginPecheDebarService {

	@Autowired
	private qEnginPecheDebarRepository captures2JpaRepository;

	
	
	@Override
	public qEnginPecheDebar findById(qEnginPechePK idCapture) {
		qEnginPecheDebar captures2Entity = captures2JpaRepository.findOne(idCapture);
		return captures2Entity ;
	}

	@Override
	public List<qEnginPecheDebar> findAll() {
		Iterable<qEnginPecheDebar> entities = captures2JpaRepository.findAll();
		List<qEnginPecheDebar> beans = new ArrayList<qEnginPecheDebar>();
		for(qEnginPecheDebar captures2Entity : entities) {
			beans.add(captures2Entity);
		}
		return beans;
	}

	@Override
	public qEnginPecheDebar save(qEnginPecheDebar captures2) {
		return update(captures2) ;
	}

	@Override
	public qEnginPecheDebar create(qEnginPecheDebar captures2) {


		qEnginPecheDebar captures2EntitySaved = captures2JpaRepository.save(captures2);
		return captures2EntitySaved;
	}

	@Override
	public qEnginPecheDebar update(qEnginPecheDebar captures2) {
		qEnginPecheDebar captures2Entity = captures2JpaRepository.findOne(captures2.getEnginPechePK());
		qEnginPecheDebar captures2EntitySaved = captures2JpaRepository.save(captures2Entity);
		return captures2EntitySaved;
	}

	@Override
	public void delete(qEnginPechePK idCapture) {
		captures2JpaRepository.delete(idCapture);
	}

	public qEnginPecheDebarRepository getCaptures2JpaRepository() {
		return captures2JpaRepository;
	}

	public void setCaptures2JpaRepository(qEnginPecheDebarRepository captures2JpaRepository) {
		this.captures2JpaRepository = captures2JpaRepository;
	}
}
