/*
 * Created on 26 sept. 2016 ( Time 10:51:46 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.gardecote.business.service.impl;
import com.gardecote.business.service.qEnginPecheService;
import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;


import com.gardecote.business.service.qEnginPecheService;

import com.gardecote.data.repository.jpa.qEnginPecheRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import com.gardecote.entities.qEnginPeche;
/**
 * Implementation of Captures2Service
 */
@Service
@Transactional
public class qEnginPecheServiceImpl implements qEnginPecheService {

	@Resource
	private qEnginPecheRepository captures2JpaRepository;

	
	
	@Override
	public qEnginPeche findById(String idCapture) {
		qEnginPeche captures2Entity = captures2JpaRepository.findOne(idCapture);
		return captures2Entity ;
	}

	@Override
	public List<qEnginPeche> findAll() {
		Iterable<qEnginPeche> entities = captures2JpaRepository.findAll();
		List<qEnginPeche> beans = new ArrayList<qEnginPeche>();
		for(qEnginPeche captures2Entity : entities) {
			beans.add(captures2Entity);
		}
		return beans;
	}

	@Override
	public qEnginPeche save(qEnginPeche captures2) {
		return update(captures2) ;
	}

	@Override
	public qEnginPeche create(qEnginPeche captures2) {
		qEnginPeche captures2Entity = captures2JpaRepository.findOne(captures2.getEngin().toString());
		if( captures2Entity != null ) {
			throw new IllegalStateException("already.exists");
		}
		//captures2Entity = new qEnginPeche();

		qEnginPeche captures2EntitySaved = captures2JpaRepository.save(captures2);
		return captures2EntitySaved;
	}

	@Override
	public qEnginPeche update(qEnginPeche captures2) {
		qEnginPeche captures2Entity = captures2JpaRepository.findOne(captures2.getEngin().toString());
		qEnginPeche captures2EntitySaved = captures2JpaRepository.save(captures2Entity);
		return captures2EntitySaved;
	}

	@Override
	public void delete(String idCapture) {
		captures2JpaRepository.delete(idCapture);
	}

	public qEnginPecheRepository getCaptures2JpaRepository() {
		return captures2JpaRepository;
	}

	public void setCaptures2JpaRepository(qEnginPecheRepository captures2JpaRepository) {
		this.captures2JpaRepository = captures2JpaRepository;
	}

	

}
