/*
 * Created on 26 sept. 2016 ( Time 10:51:46 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.gardecote.business.service.impl;
import com.gardecote.business.service.qEnginPecheMarService;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;




import com.gardecote.data.repository.jpa.qEnginPecheMarRepository;

import com.gardecote.entities.enumEngin;
import com.gardecote.entities.qEnginPecheMar;
import com.gardecote.entities.qEnginPechePK;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * Implementation of Captures2Service
 */
@Service
@Transactional
public class qEnginPecheMarServiceImpl implements qEnginPecheMarService {

	@Autowired
	private qEnginPecheMarRepository captures2JpaRepository;

	
	
	@Override
	public qEnginPecheMar findById(qEnginPechePK idCapture) {
		qEnginPecheMar captures2Entity = captures2JpaRepository.findOne(idCapture);
		return captures2Entity ;
	}

	@Override
	public List<qEnginPecheMar> findAll() {
		Iterable<qEnginPecheMar> entities = captures2JpaRepository.findAll();
		List<qEnginPecheMar> beans = new ArrayList<qEnginPecheMar>();
		for(qEnginPecheMar captures2Entity : entities) {
			beans.add(captures2Entity);
		}
		return beans;
	}

	@Override
	public qEnginPecheMar save(qEnginPecheMar captures2) {
		return update(captures2) ;
	}

	@Override
	public qEnginPecheMar create(qEnginPecheMar captures2) {
		qEnginPecheMar captures2Entity = captures2JpaRepository.findOne(captures2.getEnginPechePK());
	//	if( captures2Entity != null ) {
	//		throw new Exception("already exists");
	//	}
		//captures2Entity = new qEnginPeche();

		qEnginPecheMar captures2EntitySaved = captures2JpaRepository.save(captures2);
		return captures2EntitySaved;
	}

	@Override
	public qEnginPecheMar update(qEnginPecheMar captures2) {

		qEnginPecheMar captures2EntitySaved = captures2JpaRepository.save(captures2);
		return captures2EntitySaved;
	}

	@Override
	public void delete(qEnginPechePK idCapture) {
		captures2JpaRepository.delete(idCapture);
	}

	public qEnginPecheMarRepository getCaptures2JpaRepository() {
		return captures2JpaRepository;
	}

	public void setCaptures2JpaRepository(qEnginPecheMarRepository captures2JpaRepository) {
		this.captures2JpaRepository = captures2JpaRepository;
	}
}
