/*
 * Created on 26 sept. 2016 ( Time 10:51:46 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.gardecote.business.service.impl;
import com.gardecote.business.service.qEspeceService;
import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;

;

import com.gardecote.data.repository.jpa.qEspeceRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import com.gardecote.entities.qEspece;
/**
 * Implementation of ChangmentactService
 */
@Service
@Transactional
public class qEspeceServiceImpl implements qEspeceService {

	@Autowired
	private qEspeceRepository changmentactJpaRepository;


	@Override
	public qEspece findById(String idchact) {
		qEspece changmentactEntity = changmentactJpaRepository.findOne(idchact);
		return changmentactEntity;
	}

	@Override
	public List<qEspece> findAll() {
		Iterable<qEspece> entities = changmentactJpaRepository.findAll();
		List<qEspece> beans = new ArrayList<qEspece>();
		for(qEspece changmentactEntity : entities) {
			beans.add(changmentactEntity);
		}
		return beans;
	}

	@Override
	public qEspece save(qEspece changmentact) {
		return update(changmentact) ;
	}

	@Override
	public qEspece create(qEspece changmentact) {
		qEspece changmentactEntity = changmentactJpaRepository.findOne(changmentact.getCodeEsp());
		if( changmentactEntity != null ) {
			throw new IllegalStateException("already.exists");
		}

		qEspece changmentactEntitySaved = changmentactJpaRepository.save(changmentact);
		return changmentactEntitySaved;
	}

	@Override
	public qEspece update(qEspece changmentact) {
		qEspece changmentactEntity = changmentactJpaRepository.findOne(changmentact.getCodeEsp());

		qEspece changmentactEntitySaved = changmentactJpaRepository.save(changmentactEntity);
		return changmentactEntitySaved;
	}

	@Override
	public void delete(String idchact) {
		changmentactJpaRepository.delete(idchact);
	}

	public qEspeceRepository getChangmentactJpaRepository() {
		return changmentactJpaRepository;
	}

	public void setChangmentactJpaRepository(qEspeceRepository changmentactJpaRepository) {
		this.changmentactJpaRepository = changmentactJpaRepository;
	}

	

}
