/*
 * Created on 26 sept. 2016 ( Time 10:51:46 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.gardecote.business.service.impl;
import com.gardecote.business.service.qJourService;
import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;

import com.gardecote.business.service.qJourService;

import com.gardecote.data.repository.jpa.qJourRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import com.gardecote.entities.qJour;
/**
 * Implementation of ClassinfractionsService
 */
@Service
@Transactional
public class qJourServiceImpl implements qJourService {

	@Resource
	private qJourRepository classinfractionsJpaRepository;

	
	
	@Override
	public qJour findById(Long codeClass) {
		qJour classinfractionsEntity = classinfractionsJpaRepository.findOne(codeClass);
		return classinfractionsEntity ;
	}

	@Override
	public List<qJour> findAll() {
		Iterable<qJour> entities = classinfractionsJpaRepository.findAll();
		List<qJour> beans = new ArrayList<qJour>();
		for(qJour classinfractionsEntity : entities) {
			beans.add(classinfractionsEntity);
		}
		return beans;
	}

	@Override
	public qJour save(qJour classinfractions) {
		return update(classinfractions) ;
	}

	@Override
	public qJour create(qJour classinfractions) {
		qJour classinfractionsEntity = classinfractionsJpaRepository.findOne(classinfractions.getIdJour());
		if( classinfractionsEntity != null ) {
			throw new IllegalStateException("already.exists");
		}
		classinfractionsEntity = new qJour();
		qJour classinfractionsEntitySaved = classinfractionsJpaRepository.save(classinfractionsEntity);
		return classinfractionsEntitySaved;
	}

	@Override
	public qJour update(qJour classinfractions) {
		qJour classinfractionsEntity = classinfractionsJpaRepository.findOne(classinfractions.getIdJour());
		qJour classinfractionsEntitySaved = classinfractionsJpaRepository.save(classinfractionsEntity);
		return classinfractionsEntitySaved;
	}

	@Override
	public void delete(Long codeClass) {
		classinfractionsJpaRepository.delete(codeClass);
	}

	public qJourRepository getClassinfractionsJpaRepository() {
		return classinfractionsJpaRepository;
	}

	public void setClassinfractionsJpaRepository(qJourRepository classinfractionsJpaRepository) {
		this.classinfractionsJpaRepository = classinfractionsJpaRepository;
	}

	
}
