/*
 * Created on 26 sept. 2016 ( Time 10:51:46 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.gardecote.business.service.impl;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.*;

import com.gardecote.business.service.*;
import com.gardecote.data.repository.jpa.qRegistreNavireRepository;
import com.gardecote.dto.StatusResponse;
import com.gardecote.entities.*;
import org.apache.commons.lang.StringUtils;
import org.springframework.batch.core.Job;
import org.springframework.batch.core.JobParameter;
import org.springframework.batch.core.JobParameters;
import org.springframework.batch.core.JobParametersBuilder;
import org.springframework.batch.core.launch.JobLauncher;
import org.springframework.batch.core.repository.JobInstanceAlreadyCompleteException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import com.gardecote.data.repository.jpa.qLicenceRepository;
import org.springframework.web.multipart.MultipartFile;

import javax.servlet.http.HttpServletRequest;

/**
 * Implementation of CodauthService
 */
@Service
@Transactional
public class qLicenceServiceImpl implements qLicenceService {
	@Autowired
	JobLauncher jobLauncher;
	@Autowired
	Job licencesImportJob;
	@Autowired
	private qTypeLicService typlicService;
	@Autowired
	private qDocService docService;
	@Autowired
	private qZoneService zoneService;
	@Autowired
	private qCategRessourceService catService;
	@Autowired
	private qNationService nationRepository;
	@Autowired
	private qLicenceRepository codauthJpaRepository;
	@Autowired
	private qRegistreNavireService navService;
	@Override
	public qLic findById(String codeauth) {
		qLic codauthEntity = codauthJpaRepository.findOne(codeauth);
		return codauthEntity;
	}

	@Override
	public List<qLic> findAll() {
		Iterable<qLic> entities = codauthJpaRepository.findAll();
		List<qLic> beans = new ArrayList<qLic>();
		for(qLic qCapture1 : entities) {
			beans.add(qCapture1);
		}
		return codauthJpaRepository.lstLicences();

	}

	//@Override
	public Page<qLic> findAll(int p,int size) {
		PageRequest request= new PageRequest(p,size, Sort.Direction.DESC,"dateDebutAuth");
	//	Iterable<qLic> entities = codauthJpaRepository.findAll(new PageRequest(p, size));
		Page<qLic> entities = codauthJpaRepository.findAll(request);
	//	List<qLic> beans = new ArrayList<qLic>();
//		for(qLic codauthEntity : entities) {
	//		beans.add(codauthEntity);
//		}
	//	return beans;
		return entities;
	}

	@Override
	public qLic save(qLic codauth) {
		return update(codauth) ;
	}

	@Override
	public qLic create(qLic codauth) {
    	qLic codauthEntitySaved = codauthJpaRepository.save(codauth);
		return codauthEntitySaved ;
	}

	@Override
	public qLic update(qLic codauth) {
    	qLic codauthEntitySaved = codauthJpaRepository.save(codauth);
		return codauthEntitySaved;
	}

	@Override
	public void delete(String codeauth) {
		codauthJpaRepository.delete(codeauth);
	}

	public qLicenceRepository getCodauthJpaRepository() {
		return codauthJpaRepository;
	}

	public void setCodauthJpaRepository(qLicenceRepository codauthJpaRepository) {
		this.codauthJpaRepository = codauthJpaRepository;
	}

	public Page<qLic> returnSuggNomNav(String searchNomnav){
		return codauthJpaRepository.returnSuggNomNav1(new PageRequest(0, 10),searchNomnav);
	}

	@Override
	public boolean validatenav(qLic lic) {
		qNavire  qnv=navService.findById(lic.getNumimm());
		if(qnv==null)  return false;
		else           return true;

}

	@Override
	public List<qLic> checkNation(qNation nationjp) {
		return codauthJpaRepository.echec(nationjp);
	}

	@Override
	public boolean validatenumlic(qLic lic) {
		qLic  qlc=codauthJpaRepository.findOne(lic.getNumlic());
		if(qlc==null)  return true;
		else           return false;

	}

	@Override
	public boolean checkPrefix(qPrefix deletedPrefix) {
		if(docService.checkPrefix(deletedPrefix)==true) return true;
		else                               return false;

	}

	@Override
	public boolean checkZones(qZone zone) {
		List<qLic> licences=codauthJpaRepository.checkZone(zone);
		if(licences.size()>0) return true;
		else return false;
	}

	@Override

		public String importerLicenceNV(MultipartFile file, String fullpatchname) {

		System.out.println("jjjjj");
		try {

			file.transferTo(new File(fullpatchname));
			try {
				Map<String, JobParameter> parameters = new HashMap<String, JobParameter>();
				parameters.put("date", new JobParameter(new Date()));
				parameters.put("pathToFile", new JobParameter(fullpatchname));

				jobLauncher.run(licencesImportJob, new JobParameters(parameters));
				return "est encours";

			} catch (JobInstanceAlreadyCompleteException ex) {
				return "This job has been completed already!";

			} catch (Exception e) {
				throw new RuntimeException(e);
			}
		}  catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
return "OK";

	}
	@Override
	public void importerLicence(MultipartFile file, String fullpatchname) {
		Long nCarnet,nDebut;
		Integer ngroupe,nbrCons,nbrTotal;
		double valeurTk;
		qLic lic;
		List<qCategRessource> newCat=null;

		Long Id_Lic;
		Date createdOn=null,DEBAUT=null,FINAUTO=null;
		Integer Id_TypeLic,ID_NATION,Id_Zone,Consignataire,TYPENCAD;
		String NUMIMM,NUMENR,NUMLIC,TYPAUTO,	TYPLIC,	MINTYPLIC,	NOMNAV,	NOMEX,	NOMAR,TYPNAV,MINTYPNAV,TJB,CALPOIDS,PUIMOT,KW,LONGG,LARG,PORT,RADIO,NATION1,ANCONS,ZONE,MAIL,ENGIN,ENGIN1,MAIL1,ENGIN2,MAIL2,ENGIN3,MAIL3,EFF,NBRHOMM,COUNT,typb,imo,balise,code_type_supp_droit,id_concessionnaire,id_type_concession,id_segment_peche,ref_contrat_concession,GT;
		qLic currentLic=null;
		qNavire currentNavire=null,insertedNavire=null;
		Long k=0L;

		try {

			file.transferTo(new File(fullpatchname));
		} catch (IllegalStateException e) {
		}  catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		// Read test file.
		BufferedReader bufferedReader = null;
		try {
			FileReader reader = new FileReader(fullpatchname);
			bufferedReader = new BufferedReader(reader);
			String next, line = bufferedReader.readLine();
			for (boolean first = true, last = (line == null); !last; first = false, line = next) {
				last = ((next = bufferedReader.readLine()) == null);
				if(!first) {
					k++;
					System.out.println(k);
					newCat=new ArrayList<qCategRessource>();
					String splitarray[] = line.split("\t");
					System.out.println(splitarray[0]);
					Id_Lic=Long.valueOf(splitarray[0]);
					Id_TypeLic=Integer.valueOf(splitarray[1]);
					ID_NATION=Integer.valueOf(splitarray[2]);
					Id_Zone=Integer.valueOf(splitarray[3]);
					NUMIMM=String.valueOf(splitarray[4]);
					NUMENR=String.valueOf(splitarray[5]);
					NUMLIC=String.valueOf(splitarray[6]);
					TYPAUTO=String.valueOf(splitarray[7]);
					TYPLIC=String.valueOf(splitarray[8]);
					MINTYPLIC=String.valueOf(splitarray[9]);
					NOMNAV=String.valueOf(splitarray[10]);
					NOMEX=String.valueOf(splitarray[11]);
					NOMAR=String.valueOf(splitarray[12]);
					SimpleDateFormat sdfmt1 = new SimpleDateFormat("dd/MM/yyyy");
				//	if((!splitarray[13].equals("VIDE")) || (!splitarray[14].equals("VIDE"))) {
					try {
      					DEBAUT=sdfmt1.parse(splitarray[13]);
					} catch (ParseException e) {
						e.printStackTrace();
					}

					try {
						FINAUTO=sdfmt1.parse(splitarray[14]);
					} catch (ParseException e) {
						e.printStackTrace();
					}


					//DEBAUT=Date.valueOf(splitarray[1]);
					//FINAUTO=Date.valueOf(splitarray[1]);
					TYPNAV=String.valueOf(splitarray[15]);
					MINTYPNAV=String.valueOf(splitarray[16]);
					TJB=String.valueOf(splitarray[17]);
					CALPOIDS=String.valueOf(splitarray[18]);
					PUIMOT=String.valueOf(splitarray[19]);
					KW=String.valueOf(splitarray[20]);
					LONGG=String.valueOf(splitarray[21]);
					LARG=String.valueOf(splitarray[22]);
					PORT=String.valueOf(splitarray[23]);
					RADIO=String.valueOf(splitarray[24]);
					NATION1=String.valueOf(splitarray[25]);
					ANCONS=String.valueOf(splitarray[26]);
					ZONE=String.valueOf(splitarray[27]);
					MAIL=String.valueOf(splitarray[28]);
					ENGIN=String.valueOf(splitarray[29]);
					ENGIN1=String.valueOf(splitarray[30]);
					MAIL1=String.valueOf(splitarray[31]);
					ENGIN2=String.valueOf(splitarray[32]);
					MAIL2=String.valueOf(splitarray[33]);
					ENGIN3=String.valueOf(splitarray[34]);
					MAIL3=String.valueOf(splitarray[35]);
					EFF=String.valueOf(splitarray[36]);
					NBRHOMM=String.valueOf(splitarray[37]);
					COUNT=String.valueOf(splitarray[38]);
					typb=String.valueOf(splitarray[39]);
					Consignataire=Integer.valueOf(splitarray[40]);
					TYPENCAD=Integer.valueOf(splitarray[41]);
					GT="0";
					//
					qTypeLic typlic=typlicService.findById(Id_TypeLic);
					qNation nation=nationRepository.findById(ID_NATION);
					qZone zone=zoneService.findById(Id_Zone);
					//qCategRessource catRess=catService.findById();
					currentNavire=navService.findById(NUMIMM);
					currentNavire=null;
					qNavire newNavire=null;

					String  typeNavire=null;
					qTypeEnc encadrement=null ;

					if(MINTYPNAV.equals("A")) typeNavire=enumTypeBat.PIROG.toString();
					if(MINTYPNAV.equals("C")) typeNavire=enumTypeBat.Congelateur_glacier.toString();
					if(MINTYPNAV.equals("C1")) typeNavire=enumTypeBat.Congelateur_RTMS.toString();
					if(MINTYPNAV.equals("C2")) typeNavire=enumTypeBat.Congelateur_RTMA.toString();
					if(MINTYPNAV.equals("C3")) typeNavire=enumTypeBat.Congelateur_BMRT.toString();
					if(MINTYPNAV.equals("C4")) typeNavire=enumTypeBat.Congelateur_RTMA.toString();
					if(MINTYPNAV.equals("CG")) typeNavire=enumTypeBat.Congelateur_glacier.toString();
					if(MINTYPNAV.equals("COT")) typeNavire=enumTypeBat.Congelateur_RTMA.toString();
					if(MINTYPNAV.equals("G")) typeNavire=enumTypeBat.COTIERE.toString();
					if(MINTYPNAV.equals("GR")) typeNavire=enumTypeBat.GLACIER_Refrigeration.toString();
					if(MINTYPNAV.equals("REF")) typeNavire=enumTypeBat.REFRIGERATION.toString();
					if(MINTYPNAV.equals("SG")) typeNavire=enumTypeBat.SURGELATION.toString();
					if(MINTYPNAV.equals("V")) typeNavire=enumTypeBat.Vivier.toString();
					if(MINTYPNAV.equals("VC")) typeNavire=enumTypeBat.Vivier_Congelateur.toString();
					if(MINTYPNAV.equals("VG")) typeNavire=enumTypeBat.Vivier_Glacier.toString();
					if(MINTYPNAV.equals("REF")) typeNavire=enumTypeBat.REF.toString();
					if(MINTYPNAV.equals("C.F.")) typeNavire=enumTypeBat.Congelateur_Refrigerateur.toString();
					if(MINTYPNAV.equals("INDEF")) typeNavire=enumTypeBat.INDEF.toString();
					if(MINTYPNAV.equals("0")) typeNavire=enumTypeBat.INDEF.toString();


					if(MINTYPNAV.equals("INDEF")) typeNavire=enumTypeBat.INDEF.toString();

					if(TYPENCAD==1)   encadrement=qTypeEnc.MRT;
					if(TYPENCAD==2)   encadrement=qTypeEnc.ASIATIQUE;
					if(TYPENCAD==3)   encadrement=qTypeEnc.UE;
					if(TYPENCAD==4)   encadrement=qTypeEnc.AFRIC;
					if(TYPENCAD==5)   encadrement=qTypeEnc.Autres;
					if(TYPENCAD==0)   encadrement=qTypeEnc.INDET;
					if(TYPENCAD==-1)  encadrement=qTypeEnc.INDET;

					if(TYPENCAD==1)
					{
						if(currentNavire!=null) {
							insertedNavire=currentNavire;
							createdOn=currentNavire.getUpdatedOn();
							System.out.println(createdOn);
							System.out.println(DEBAUT);
							if(createdOn.before(DEBAUT))
							{   currentNavire.setNomnav(NOMNAV);
								currentNavire.setUpdatedOn(DEBAUT);
								navService.update(currentNavire);}
						}
						else
						{
							newNavire=new qNavire(NUMIMM,NOMNAV, NOMAR, LONGG, PUIMOT, nation, LARG, COUNT, NBRHOMM, EFF, 0, CALPOIDS, 0,0,0, 0, PORT, RADIO,"0",DEBAUT);
							navService.create(newNavire);
							insertedNavire=newNavire;
						}

						currentLic=new qLicenceNational(typlic, zone, nation, null, insertedNavire,enumTypeBat.valueOf(typeNavire), DEBAUT, FINAUTO, 0,"0",CALPOIDS, COUNT, EFF, 0, 0,0, LARG, LONGG,NBRHOMM, NOMAR, NOMNAV, NUMLIC, PORT,PUIMOT, RADIO, 0,null,null);
					}
					else {
						System.out.println("type navire :"+typeNavire);
						System.out.println("type navire :"+MINTYPNAV);
						System.out.println("num lic :"+NUMLIC);
						if(currentNavire!=null) {
							insertedNavire=currentNavire;
							createdOn=currentNavire.getUpdatedOn();
							if(createdOn.before(DEBAUT))
							{currentNavire.setNomnav(NOMNAV);
								currentNavire.setUpdatedOn(DEBAUT);
								navService.save(currentNavire);}
						}
						else
						{

							newNavire=new qNavire(NUMIMM,NOMNAV, NOMAR, LONGG, PUIMOT, nation, LARG, COUNT, NBRHOMM, EFF, 0, CALPOIDS, 0,0,0, 0, PORT, RADIO,"0",DEBAUT);
							navService.create(newNavire);
							insertedNavire=newNavire;
						}

						currentLic=new qLicenceLibre(typlic, zone, nation, null, insertedNavire,enumTypeBat.valueOf(typeNavire), DEBAUT, FINAUTO, 0,"0",CALPOIDS, COUNT, EFF, 0, 0,0, LARG, LONGG,NBRHOMM, NOMAR, NOMNAV, NUMLIC, PORT,PUIMOT, RADIO, 0,encadrement,null);

				}
					codauthJpaRepository.save(currentLic);
					System.out.println("l'index est : "+k);
				}
				k++;

			}


			reader.close();

		}
		catch (IOException e) {
			e.printStackTrace();
		}
		finally {
			if (bufferedReader!= null) try { bufferedReader.close(); } catch (IOException logOrIgnore) {}
		}
	}


}
