/*
 * Created on 26 sept. 2016 ( Time 10:51:46 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.gardecote.business.service.impl;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;



import com.gardecote.data.repository.jpa.qLicenceBatLastRepository;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import com.gardecote.business.service.qLicenceBatLastService;
import com.gardecote.entities.qLicenceBatLast;
/**
 * Implementation of CodauthService
 */
@Service
@Transactional
public class qLicenceBatLastServiceImpl implements qLicenceBatLastService {

	@Resource
	private qLicenceBatLastRepository codauthJpaRepository;

	@Override
	public qLicenceBatLast findById(Long codeauth) {
		qLicenceBatLast codauthEntity = codauthJpaRepository.findOne(codeauth);
		return codauthEntity;
	}

	@Override
	public List<qLicenceBatLast> findAll() {
		Iterable<qLicenceBatLast> entities = codauthJpaRepository.findAll();
		List<qLicenceBatLast> beans = new ArrayList<qLicenceBatLast>();
		for(qLicenceBatLast codauthEntity : entities) {
			beans.add(codauthEntity);
		}
		return beans;
	}

	@Override
	public qLicenceBatLast save(qLicenceBatLast codauth) {
		return update(codauth) ;
	}

	@Override
	public qLicenceBatLast create(qLicenceBatLast codauth) {
		qLicenceBatLast codauthEntity = codauthJpaRepository.findOne(codauth.getIdLic());
		if( codauthEntity != null ) {
			throw new IllegalStateException("already.exists");
		}
		codauthEntity = new qLicenceBatLast();

		qLicenceBatLast codauthEntitySaved = codauthJpaRepository.save(codauthEntity);
		return codauthEntitySaved ;
	}

	@Override
	public qLicenceBatLast update(qLicenceBatLast codauth) {
		qLicenceBatLast codauthEntity = codauthJpaRepository.findOne(codauth.getIdLic());

		qLicenceBatLast codauthEntitySaved = codauthJpaRepository.save(codauthEntity);
		return codauthEntitySaved;
	}

	@Override
	public void delete(Long codeauth) {
		codauthJpaRepository.delete(codeauth);
	}

	public qLicenceBatLastRepository getCodauthJpaRepository() {
		return codauthJpaRepository;
	}

	public void setCodauthJpaRepository(qLicenceBatLastRepository codauthJpaRepository) {
		this.codauthJpaRepository = codauthJpaRepository;
	}

	public Page<qLicenceBatLast> returnSuggNomNav(String searchNomnav){
		return codauthJpaRepository.returnSuggNomNav1(new PageRequest(0, 10),searchNomnav);
	}

}
