/*
 * Created on 26 sept. 2016 ( Time 10:51:46 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.gardecote.business.service.impl;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;




import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.gardecote.entities.qLicence;
import com.gardecote.business.service.qLicenceService;
import com.gardecote.data.repository.jpa.qLicenceRepository;
/**
 * Implementation of CodauthService
 */
@Service
@Transactional
public class qLicenceServiceImpl implements qLicenceService {

	@Resource
	private qLicenceRepository codauthJpaRepository;

	@Override
	public qLicence findById(Long codeauth) {
		qLicence codauthEntity = codauthJpaRepository.findOne(codeauth);
		return codauthEntity;
	}

	@Override
	public List<qLicence> findAll() {
		Iterable<qLicence> entities = codauthJpaRepository.findAll();
		List<qLicence> beans = new ArrayList<qLicence>();
		for(qLicence codauthEntity : entities) {
			beans.add(codauthEntity);
		}
		return beans;
	}

	@Override
	public qLicence save(qLicence codauth) {
		return update(codauth) ;
	}

	@Override
	public qLicence create(qLicence codauth) {
		qLicence codauthEntity = codauthJpaRepository.findOne(codauth.getIdLic());
		if( codauthEntity != null ) {
			throw new IllegalStateException("already.exists");
		}
		codauthEntity = new qLicence();

		qLicence codauthEntitySaved = codauthJpaRepository.save(codauthEntity);
		return codauthEntitySaved ;
	}

	@Override
	public qLicence update(qLicence codauth) {
		qLicence codauthEntity = codauthJpaRepository.findOne(codauth.getIdLic());

		qLicence codauthEntitySaved = codauthJpaRepository.save(codauthEntity);
		return codauthEntitySaved;
	}

	@Override
	public void delete(Long codeauth) {
		codauthJpaRepository.delete(codeauth);
	}

	public qLicenceRepository getCodauthJpaRepository() {
		return codauthJpaRepository;
	}

	public void setCodauthJpaRepository(qLicenceRepository codauthJpaRepository) {
		this.codauthJpaRepository = codauthJpaRepository;
	}

	public Page<qLicence> returnSuggNomNav(String searchNomnav){
		return codauthJpaRepository.returnSuggNomNav1(new PageRequest(0, 10),searchNomnav);
	}

}
