/*
 * Created on 26 sept. 2016 ( Time 10:51:47 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.gardecote.business.service.impl;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;
import com.gardecote.data.repository.jpa.qMareeRepository;
import com.gardecote.business.service.qMarreeService;


import com.gardecote.entities.enumTypeDoc;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import com.gardecote.entities.qMarree;
import com.gardecote.entities.qDocPK;
/**
 * Implementation of CodeInfractionsService
 */

@Service
@Transactional
public class qMareeServiceImpl implements qMarreeService {

	@Resource
	private qMareeRepository codeInfractionsJpaRepository;

	
	
	@Override
	public  qMarree findById(qDocPK code) {
		qMarree codeInfractionsEntity = codeInfractionsJpaRepository.findOne(code);
		return codeInfractionsEntity;
	}

	@Override
	public List<qMarree> findAll() {
		Iterable<qMarree> entities = codeInfractionsJpaRepository.findAll();
		List<qMarree> beans = new ArrayList<qMarree>();
		for(qMarree codeInfractionsEntity : entities) {
			beans.add(codeInfractionsEntity);
		}
		return beans;
	}

	@Override
	public qMarree save(qMarree codeInfractions) {
		return update(codeInfractions) ;
	}

	@Override
	public qMarree create(qMarree codeInfractions) {
		qMarree codeInfractionsEntity = codeInfractionsJpaRepository.findOne(codeInfractions.getqDocPK());
		if( codeInfractionsEntity != null ) {
			throw new IllegalStateException("already.exists");
		}
		//codeInfractionsEntity = new qMarree(enumTypeDoc.Journal_Peche,null);
		qMarree codeInfractionsEntitySaved = codeInfractionsJpaRepository.save(codeInfractions);
		return codeInfractionsEntitySaved ;
	}

	@Override
	public qMarree update(qMarree codeInfractions) {
		qMarree codeInfractionsEntity = codeInfractionsJpaRepository.findOne(codeInfractions.getqDocPK());
		qMarree codeInfractionsEntitySaved = codeInfractionsJpaRepository.save(codeInfractionsEntity);
		return codeInfractionsEntitySaved;
	}

	@Override
	public void delete(qDocPK code) {
		codeInfractionsJpaRepository.delete(code);
	}

	public qMareeRepository getCodeInfractionsJpaRepository() {
		return codeInfractionsJpaRepository;
	}

	public void setCodeInfractionsJpaRepository(qMareeRepository codeInfractionsJpaRepository) {
		this.codeInfractionsJpaRepository = codeInfractionsJpaRepository;
	}

	

}
