/*
 * Created on 26 sept. 2016 ( Time 10:51:48 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.gardecote.business.service.impl;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

import javax.annotation.Resource;
import com.gardecote.data.repository.jpa.qPageCarnetRepository;

import com.gardecote.entities.enumTypeDoc;
import com.gardecote.entities.qCarnet;
import com.gardecote.entities.qPageCarnetPK;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import com.gardecote.business.service.qPageCarnetService;
import com.gardecote.entities.qPageCarnet;
import com.gardecote.data.repository.jpa.qCarnetRepository;
/**
 * Implementation of CodesEspService
 */
@Service
@Transactional
public class qPageCarnetServiceImpl implements qPageCarnetService {

	@Autowired
	private qPageCarnetRepository qPageCarnetRepository;
	@Autowired
	private qCarnetRepository qcarnetRepository;

		
	@Override
	public qPageCarnet findById(qPageCarnetPK codesp) {
		qPageCarnet codesEspEntity = qPageCarnetRepository.findOne(codesp);
		return codesEspEntity;
	}

	@Override
	public List<qPageCarnet> findAll() {
		Iterable<qPageCarnet> entities = qPageCarnetRepository.findAll();
	//	Iterable<qPageCarnet>
		List<qPageCarnet> beans =new ArrayList<qPageCarnet>();
		for(qPageCarnet codesEspEntity : entities) {
			beans.add(codesEspEntity);
		}
		return beans;
	}

	@Override
	public qPageCarnet save(qPageCarnet codesEsp) {
		return update(codesEsp) ;
	}

	@Override
	public qPageCarnet create(qPageCarnet codesEsp) {

		qPageCarnet codesEspEntitySaved = qPageCarnetRepository.save(codesEsp);
		return codesEspEntitySaved;
	}

	@Override
	public qPageCarnet update(qPageCarnet codesEsp) {
		qPageCarnet codesEspEntity = qPageCarnetRepository.findOne(codesEsp.getPageCarnetPK());

		qPageCarnet codesEspEntitySaved = qPageCarnetRepository.save(codesEspEntity);
		return codesEspEntitySaved;
	}

	@Override
	public void delete(qPageCarnetPK codesp) {
		qPageCarnetRepository.delete(codesp);
	}

	public qPageCarnetRepository getCodesEspJpaRepository() {
		return qPageCarnetRepository;
	}

	public void setCodesEspJpaRepository(qPageCarnetRepository codesEspJpaRepository) {
		this.qPageCarnetRepository = codesEspJpaRepository;
	}

	@Override
	public Page<qPageCarnet> getSuggPage(String searchpage,enumTypeDoc typeDoc) {
		return qPageCarnetRepository.returnSuggPage(new PageRequest(0, 10),searchpage,typeDoc);
	}
	@Override
	public Page<qPageCarnet> getSuggPageAnnexe(String searchpage,enumTypeDoc typeDoc) {
		return qPageCarnetRepository.returnSuggPageAnnexe(new PageRequest(0, 10),searchpage,typeDoc);
	}
	@Override
	public ArrayList<qPageCarnet> getFinList(String debut,enumTypeDoc typeDoc) {
		qCarnet carnet=qcarnetRepository.retCarnet(debut,typeDoc);
//		qPageCarnet gg=qPageCarnetRepository.findOne(debut);
//		qCarnet carnet=gg.getQcarnet();
		Long dd=qcarnetRepository.retNumOrdre(debut,typeDoc);
		System.out.println(dd);
		System.out.println(carnet.getPrefixNumerotation());
		return qPageCarnetRepository.returnFinList(carnet,dd);
	}
}
