/*
 * Created on 26 sept. 2016 ( Time 10:51:48 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.gardecote.business.service.impl;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;
import com.gardecote.data.repository.jpa.qPageCarnetRepository;

import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import com.gardecote.business.service.qPageCarnetService;
import com.gardecote.entities.qPageCarnet;
/**
 * Implementation of CodesEspService
 */
@Service
@Transactional
public class qPageCarnetServiceImpl implements qPageCarnetService {

	@Resource
	private qPageCarnetRepository qPageCarnetRepository;

		
	@Override
	public qPageCarnet findById(String codesp) {
		qPageCarnet codesEspEntity = qPageCarnetRepository.findOne(codesp);
		return codesEspEntity;
	}

	@Override
	public List<qPageCarnet> findAll() {
		Iterable<qPageCarnet> entities = qPageCarnetRepository.findAll();
		List<qPageCarnet> beans = new ArrayList<qPageCarnet>();
		for(qPageCarnet codesEspEntity : entities) {
			beans.add(codesEspEntity);
		}
		return beans;
	}

	@Override
	public qPageCarnet save(qPageCarnet codesEsp) {
		return update(codesEsp) ;
	}

	@Override
	public qPageCarnet create(qPageCarnet codesEsp) {
		qPageCarnet codesEspEntity = qPageCarnetRepository.findOne(codesEsp.getNumeroPage());
		if( codesEspEntity != null ) {
			throw new IllegalStateException("already.exists");
		}
		codesEspEntity = new qPageCarnet();
		qPageCarnet codesEspEntitySaved = qPageCarnetRepository.save(codesEspEntity);
		return codesEspEntitySaved;
	}

	@Override
	public qPageCarnet update(qPageCarnet codesEsp) {
		qPageCarnet codesEspEntity = qPageCarnetRepository.findOne(codesEsp.getNumeroPage());

		qPageCarnet codesEspEntitySaved = qPageCarnetRepository.save(codesEspEntity);
		return codesEspEntitySaved;
	}

	@Override
	public void delete(String codesp) {
		qPageCarnetRepository.delete(codesp);
	}

	public qPageCarnetRepository getCodesEspJpaRepository() {
		return qPageCarnetRepository;
	}

	public void setCodesEspJpaRepository(qPageCarnetRepository codesEspJpaRepository) {
		this.qPageCarnetRepository = codesEspJpaRepository;
	}

	

}
