/*
 * Created on 26 sept. 2016 ( Time 10:51:46 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.gardecote.business.service.impl;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.ArrayList;
import java.util.List;
import com.gardecote.business.service.qTypeConcessionService;


/**
 * Implementation of ActivitebatService
 */
import com.gardecote.entities.qTypeConcession;
import com.gardecote.data.repository.jpa.qTypeConcessionRepository;
@Service
@Transactional
public class qTypeConcessionServiceImpl implements qTypeConcessionService {

	@Autowired
	private qTypeConcessionRepository qTypeConcessionJpaRepository;

	
	@Override
	public qTypeConcession findById(Integer idcapt) {
		qTypeConcession qCaptures = qTypeConcessionJpaRepository.findOne(idcapt);
		return qCaptures;
	}

	@Override
	public List<qTypeConcession> findAll() {
		Iterable<qTypeConcession> entities = qTypeConcessionJpaRepository.findAll();
		List<qTypeConcession> beans = new ArrayList<qTypeConcession>();
		for(qTypeConcession qCapture1 : entities) {
			beans.add(qCapture1);
		}
		return beans;
	}

	@Override
	public qTypeConcession save(qTypeConcession qcapture) {
		return update(qcapture) ;
	}

	@Override
	public qTypeConcession create(qTypeConcession qcapture) {


		//qcaptureEntity = new qCategRessource();
		qTypeConcession qcaptureEntitySaved = qTypeConcessionJpaRepository.save(qcapture);
		return qcaptureEntitySaved ;
	}

	@Override
	public qTypeConcession update(qTypeConcession qcapture) {
		qTypeConcession qcaptureEntity = qTypeConcessionJpaRepository.findOne(qcapture.getQtypeconcessionpk());
		qTypeConcession qcaptureEntitySaved = qTypeConcessionJpaRepository.save(qcaptureEntity);
		return qcaptureEntitySaved;
	}

	@Override
	public void delete(Integer idcapt) {
		qTypeConcessionJpaRepository.delete(idcapt);
	}


	public qTypeConcessionRepository getqCapturesJpaRepository() {
		return qTypeConcessionJpaRepository;
	}

	public void setqCapturesJpaRepository(qTypeConcessionRepository qCapturesJpaRepository) {
		this.qTypeConcessionJpaRepository = qCapturesJpaRepository;
	}
}
