/*
 * Created on 26 sept. 2016 ( Time 10:51:47 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.gardecote.business.service.impl;

import java.util.ArrayList;
import java.util.List;
import com.gardecote.entities.qZone;
import javax.annotation.Resource;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import com.gardecote.business.service.qZoneService;
import com.gardecote.data.repository.jpa.qZoneRepository;
/**
 * Implementation of CodesNotifAmService
 */
@Service
@Transactional
public class qZoneServiceImpl implements qZoneService {

	@Autowired
	private qZoneRepository codesNotifAmJpaRepository;

	@Override
	public qZone findById(Integer code) {
		qZone codesNotifAmEntity = codesNotifAmJpaRepository.findOne(code);
		return codesNotifAmEntity;
	}

	@Override
	public List<qZone> findAll() {
		Iterable<qZone> entities = codesNotifAmJpaRepository.findAll();
		List<qZone> beans = new ArrayList<qZone>();
		for(qZone codesNotifAmEntity : entities) {
			beans.add(codesNotifAmEntity);
		}
		return beans;
	}

	@Override
	public qZone save(qZone codesNotifAm) {
		return update(codesNotifAm) ;
	}

	@Override
	public qZone create(qZone codesNotifAm) {
		qZone codesNotifAmEntity = codesNotifAmJpaRepository.findOne(codesNotifAm.getIdZone());
		if( codesNotifAmEntity != null ) {
			throw new IllegalStateException("already.exists");
		}
	//	codesNotifAmEntity = new qZone();
		qZone codesNotifAmEntitySaved = codesNotifAmJpaRepository.save(codesNotifAm);
		return codesNotifAmEntitySaved;
	}

	@Override
	public qZone update(qZone codesNotifAm) {
		qZone codesNotifAmEntity = codesNotifAmJpaRepository.findOne(codesNotifAm.getIdZone());
		qZone codesNotifAmEntitySaved = codesNotifAmJpaRepository.save(codesNotifAmEntity);
		return codesNotifAmEntitySaved;
	}

	@Override
	public void delete(Integer code) {
		codesNotifAmJpaRepository.delete(code);
	}

	public qZoneRepository qZoneRepository() {
		return codesNotifAmJpaRepository;
	}

	public void setCodesNotifAmJpaRepository(qZoneRepository codesNotifAmJpaRepository) {
		this.codesNotifAmJpaRepository = codesNotifAmJpaRepository;
	}

	

}
